# Generated by Django 5.0.3 on 2024-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('vendor', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle', models.SlugField(max_length=255, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('draft', 'draft')], default='active', max_length=50)),
                ('tags', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('taxable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('disabled', 'disabled'), ('invited', 'invited'), ('enabled', 'enabled'), ('declined', 'declined')], default='disabled', max_length=10),
        ),
    ]
