# Generated by Django 5.0.3 on 2024-07-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_giftcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('active', 'active'), ('declined', 'declined'), ('expired', 'expired')], default='pending', max_length=20)),
                ('test', models.BooleanField(null=True)),
                ('updated_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
    ]
