# Generated by Django 5.0.3 on 2024-07-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_billing_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='decoration_return_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
