# Generated by Django 5.0.3 on 2024-07-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_billing_decoration_return_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodeCreationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rule_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('codes_count', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('logs', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('creation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='customer.discountcodecreationjob')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('financial_status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='pending', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('partial', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled')], default='unfulfilled', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discounts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('note', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('items', models.JSONField(default=list)),
                ('shipping_title', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='customer.address')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customer.customer')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='customer.address')),
            ],
        ),
    ]
